[project]
authors = ["Vincent D. Warmerdam"]
channels = ["conda-forge"]
description = "Rethinking machine learning pipelines a bit."
name = "scikit-playtime"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]
version = "0.1.1"

[dependencies]
python = ">=3.9,<4"
scikit-learn = ">=1.0"
narwhals = ">=0.8.14"
skrub = ">=0.1.0"
polars = ">=0.20.26,<2"

[feature.lint.dependencies]
pre-commit = "*"

[feature.tests.dependencies]
pytest = "*"

[environments]
lint = ["lint"]
tests = ["tests"]
dev = ["tests", "lint"]
