[project]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>"]
channels = ["conda-forge"]
description = "This is my pixi workspace to work on scikit-learn"
name = "scikit-learn-workspace"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0.dev0"

[tasks]
update-submodule-joblib = { cmd = "git submodule update --init --recursive", cwd = "src/joblib/joblib" }
update-submodule-threadpoolctl = { cmd = "git submodule update --init --recursive", cwd = "src/threadpoolctl/threadpoolctl" }
update-submodule-sklearn = { cmd = "git submodule update --init --recursive", cwd = "src/scikit-learn/scikit-learn" }
update-submodule-imblearn = { cmd = "git submodule update --init --recursive", cwd = "src/imbalanced-learn" }
update-all-submodules = { cmd = "echo 'Initializing all submodules'", depends-on = ["update-submodule-joblib", "update-submodule-threadpoolctl", "update-submodule-sklearn", "update-submodule-imblearn"] }
