[project]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>"]
channels = ["conda-forge"]
description = "This is my pixi workspace to work on scikit-learn"
name = "scikit-learn-workspace"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0.dev0"

[tasks]
update-submodule-joblib = { cmd = "git submodule update --init --recursive", cwd = "src/joblib/joblib" }
update-submodule-threadpoolctl = { cmd = "git submodule update --init --recursive", cwd = "src/threadpoolctl/threadpoolctl" }
update-submodule-sklearn = { cmd = "git submodule update --init --recursive", cwd = "src/scikit-learn/scikit-learn" }
update-submodule-imblearn = { cmd = "git submodule update --init --recursive", cwd = "src/imbalanced-learn" }
update-submodule-skrub = { cmd = "git submodule update --init --recursive", cwd = "src/skrub" }
update-submodule-playtime = { cmd = "git submodule update --init --recursive", cwd = "src/scikit-playtime/scikit-playtime" }
update-submodule-sklearn-compat = { cmd = "git submodule update --init --recursive", cwd = "src/sklearn_compat" }
update-submodule-lightgbm = { cmd = "git submodule update --init --recursive", cwd = "src/lightgbm" }
update-all-submodules = { cmd = "echo 'Initializing all submodules'", depends-on = ["update-submodule-joblib", "update-submodule-threadpoolctl", "update-submodule-sklearn", "update-submodule-imblearn", "update-submodule-skrub", "update-submodule-playtime", "update-submodule-sklearn-compat", "update-submodule-lightgbm" ] }

update-main-joblib = { cmd = "git checkout main && git pull", cwd = "src/joblib/joblib" }
update-main-threadpoolctl = { cmd = "git checkout master && git pull", cwd = "src/threadpoolctl/threadpoolctl" }
update-main-sklearn = { cmd = "git checkout main && git pull", cwd = "src/scikit-learn/scikit-learn" }
update-main-imblearn = { cmd = "git checkout master && git pull", cwd = "src/imbalanced-learn" }
update-main-playtime = { cmd = "git checkout main && git pull", cwd = "src/scikit-playtime/scikit-playtime" }
update-main-skrub = { cmd = "git checkout main && git pull", cwd = "src/skrub" }
update-main-sklearn-compat = { cmd = "git checkout main && git pull", cwd = "src/sklearn_compat" }
update-main-lightgbm = { cmd = "git checkout master && git pull", cwd = "src/lightgbm" }
update-main-all = { cmd = "echo 'Updating all main branches'", depends-on = ["update-main-joblib", "update-main-threadpoolctl", "update-main-sklearn", "update-main-imblearn", "update-main-playtime", "update-main-skrub", "update-main-sklearn-compat", "update-main-lightgbm"] }
