[project]
authors = ["skore developers <skore@signal.probabl.ai>"]
channels = ["conda-forge"]
description = "Tooling and assistance for data scientists to \"Own Your Data Science\""
name = "skore"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]
version = "0.1.0.dev0"

[dependencies]
python = ">=3.9,<4"
diskcache = "*"
fastapi = "*"
plotly = ">=5,<6"
pyarrow = "*"
rich = "*"
scikit-learn = "<1.7"
uvicorn = "*"

[pypi-dependencies]
skops = "*"
skore = { path = "./skore/skore", editable = true }

[feature.build.dependencies]
hatch = "*"

[feature.build.tasks]
clean-skore-ui = { cmd = "rm -rf skore-ui/dist && rm -rf src/skore/ui/static", cwd = "skore" }
build-skore-ui = { cmd = "npm install && npm run build", cwd = "skore/skore-ui" , depends-on = ["clean-skore-ui"]}
move-skore-ui = { cmd = "mv skore-ui/dist/ skore/src/skore/ui/static", cwd = "skore" , depends-on = ["build-skore-ui"]}

[feature.dev.dependencies]
ipykernel = "*"
ipython = "*"
jupyterlab = "*"
pre-commit = "*"
ruff = "*"

[feature.tests.dependencies]
altair = ">=5,<6"
httpx = "*"
matplotlib = "*"
pandas = "*"
pillow = "*"
plotly = "*"
polars = "*"
pre-commit = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
pytest-order = "*"
pytest-randomly = "*"
ruff = "*"
skrub = "*"

[feature.tests.tasks]
tests = { cmd = "pytest -vsl --cov=skore --cov-report=xml", cwd = "skore/skore/tests" }

[feature.docs.dependencies]
IPython = "*"
altair = "*"
matplotlib = "*"
numpydoc = "*"
pandas = "*"
polars = "*"
python-kaleido = "*"
pydata-sphinx-theme = "*"
sphinx = "*"
sphinx-design = "*"
sphinx-gallery = "*"
sphinx-copybutton = "*"
sphinx-tabs = "*"
skrub = "*"

[feature.docs.tasks]
docs = { cmd = "make html", cwd = "skore/sphinx" }

[feature.lint.dependencies]
black = "==24.3.0"
ruff = "==0.5.1"
cython-lint = "==0.15.0"
pre-commit = "*"

[feature.lint.tasks]
lint = { cmd = "pre-commit install && pre-commit run -v --all-files --show-diff-on-failure", cwd = "skore" }

[environments]
tests = ["tests"]
docs = ["docs"]
lint = ["lint"]
dev = ["build", "dev", "docs", "tests", "lint"]
