[project]
authors = ["Yu Shi <yushi@microsoft.com>"]
channels = ["conda-forge"]
description = "LightGBM Python-package"
name = "lightgbm"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]
version = "4.5.0.99"
