[project]
authors = ["G. Lemaitre <g.lemaitre58@gmail.com>", "C. Aridas <ichkoar@gmail.com>"]
channels = ["conda-forge"]
description = "Toolbox for imbalanced dataset in machine learning"
name = "imbalanced-learn"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]
version = "0.11.0.dev0"

[dependencies]
python = ">=3.9,<4"
numpy = ">=1.24.3,<3"
scipy = ">=1.10.1,<2"
scikit-learn = ">=1.2.2,<2"
joblib = ">=1.1.1,<2"
threadpoolctl = ">=2.0.0,<4"

[feature.build.dependencies]
pip = ">=24.2,<25"

[feature.build.pypi-options]
no-build-isolation = ["imbalanced-learn"]

[feature.build.pypi-dependencies]
imbalanced-learn = { path = "./imbalanced-learn", editable = true }

[feature.dev.dependencies]
compilers = ">=1.7.0,<2"
cython = ">=3.0.10,<4"
meson = ">=1.5.1,<2"
meson-python = ">=0.16.0,<0.17"
ipykernel = "*"
ipython = "*"
jupyterlab = "*"

[feature.dev.tasks]
ipython = { cmd = "ipython", cwd = "imbalanced-learn" }

[feature.docs.dependencies]
pandas = ">=1.5.3,<3"
matplotlib = ">=3.7.3,<4"
seaborn = ">=0.12.2,<1"
memory_profiler = ">=0.61.0,<1"
numpydoc = ">=1.5.0,<2"
sphinx = ">=8.0.2,<9"
sphinx-gallery = ">=0.13.0,<1"
sphinxcontrib-bibtex = ">=2.6.3,<3"
sphinx-copybutton = ">=0.5.2,<1"
pydata-sphinx-theme = ">=0.15.4,<1"
sphinx-design = ">=0.6.1,<1"

[feature.docs.tasks]
docs = { cmd = "make html", cwd = "imbalanced-learn/doc" }

[feature.lint.dependencies]
black = "==24.3.0"
ruff = "==0.5.1"
cython-lint = "==0.15.0"
pre-commit = "*"

[feature.lint.tasks]
lint = { cmd = "pre-commit install && pre-commit run -v --all-files --show-diff-on-failure", cwd = "imbalanced-learn" }

[feature.optional.dependencies]
pandas = ">=1.5.3,<3"

[feature.tensorflow.dependencies]
tensorflow = ">=2.13.1,<3"

[feature.keras.dependencies]
keras = ">=3.0.5,<4"

[feature.tests.dependencies]
packaging = ">=23.2,<25"
pytest = ">=7.2.2,<9"
pytest-cov = ">=4.1.0,<6"
pytest-xdist = ">=3.5.0,<4"

[feature.tests.tasks]
tests = { cmd = "pytest -vsl --cov=imblearn --cov-report=xml", cwd = "imbalanced-learn" }

[environments]
lint = ["lint"]
docs = ["build", "docs"]
dev = ["build", "dev", "docs", "optional", "keras", "lint", "tests"]
tests = ["build", "tests"]
