[project]
authors = ["Patricio Cerda <patricio.cerda@inria.fr>"]
channels = ["conda-forge"]
description = "Prepping tables for machine learning"
name = "skrub"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]
version = "0.4.0.dev0"

[dependencies]
python = ">=3.9,<4"
numpy = ">=1.23.5,<3"
packaging = ">=23.1,<25"
scipy = ">=1.9.3,<2"
scikit-learn = ">=1.2.1,<2"
pandas = ">=1.5.3,<3"
jinja2 = ">=3.1.2,<4"
matplotlib = ">=3.4.3,<4"

[feature.build.dependencies]
pip = ">=24.2,<25"

[feature.build.pypi-options]
no-build-isolation = ["skrub"]

[feature.build.pypi-dependencies]
skrub = { path = "./skrub", editable = true }

[feature.dev.dependencies]
compilers = ">=1.7.0,<2"
cython = ">=3.0.10,<4"
meson = ">=1.5.1,<2"
meson-python = ">=0.16.0,<0.17"
ipykernel = "*"
ipython = "*"
jupyterlab = "*"

[feature.dev.tasks]
ipython = { cmd = "ipython", cwd = "skrub" }

[feature.docs.dependencies]
jupyterlite-sphinx = ">=0.16.5,<1"
jupyterlite-pyodide-kernel = ">=0.4.3,<1"
numpydoc = ">=1.5.0,<2"
pydata-sphinx-theme = ">=0.15.4,<1"
seaborn = ">=0.12.2,<1"
sphinx = ">=8.0.2,<9"
sphinx-copybutton = ">=0.5.2,<1"
sphinx-gallery = ">=0.13.0,<1"
sphinxext-opengraph = ">=0.6.1,<1"
statsmodels = ">=0.13.5,<1"
pyarrow = ">=13.0.0"

[feature.docs.tasks]
docs = { cmd = "make html", cwd = "skrub/doc" }

[feature.optional.dependencies]
polars = ">=1.0.0,<2"
pyarrow = ">=13.0.0"

[feature.lint.dependencies]
black = "==24.3.0"
ruff = "==0.5.1"
pre-commit = "*"

[feature.lint.tasks]
lint = { cmd = "pre-commit install && pre-commit run -v --all-files --show-diff-on-failure", cwd = "skrub" }

[feature.tests.dependencies]
packaging = ">=23.2,<25"
pytest = ">=7.2.2,<9"
pytest-cov = ">=4.1.0,<6"
pytest-xdist = ">=3.5.0,<4"

[feature.tests.tasks]
tests = { cmd = "pytest -vsl --cov=skrub --cov-report=xml", cwd = "skrub" }

[environments]
lint = ["lint"]
docs = ["build", "optional", "docs"]
tests = ["build", "optional", "tests"]
dev = ["build", "dev", "optional", "docs", "lint", "tests"]
