[project]
authors = ["scikit-learn developers <scikit-learn@python.org>"]
channels = ["conda-forge"]
description = "A set of python modules for machine learning and data mining"
name = "scikit-learn"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]
version = "1.6.0.dev0"

[dependencies]
python = ">=3.9,<4"
numpy = ">=1.19.5,<3"
scipy = ">=1.6.0,<2"
joblib = ">=1.2.0,<2"
threadpoolctl = ">=3.1.0,<4"

[feature.build.dependencies]
compilers = ">=1.7.0,<2"
cython = ">=3.0.10,<4"
meson = ">=1.5.1,<2"
meson-python = ">=0.16.0,<0.17"
pip = ">=24.2,<25"

[feature.build.pypi-options]
no-build-isolation = ["scikit-learn"]

[feature.build.pypi-dependencies]
scikit-learn = { path = "./scikit-learn", editable = true }

[feature.build.tasks]
clean = { cmd = "spin clean", cwd = "scikit-learn" }

[feature.dev.dependencies]
ipykernel = "*"
ipython = "*"
jupyterlab = "*"
spin = "*"
towncrier = "*"

[feature.dev.tasks]
ipython = { cmd = "spin ipython", cwd = "scikit-learn" }

[feature.docs.dependencies]
sphinx = ">=7.3.7"
sphinx-copybutton = ">=0.5.2"
sphinx-gallery = ">=0.17.1"
sphinx-prompt = ">=1.4.0"
sphinxext-opengraph = ">=0.9.1"
sphinx-design = ">=0.6.0"
pydata-sphinx-theme = ">=0.15.3"
sphinx-remove-toctrees = ">=1.0.0.post1"
numpydoc = ">=1.2.0"
matplotlib = ">=3.3.4"
scikit-image = ">=0.17.2"
pandas = ">=1.1.5"
seaborn = ">=0.9.0"
plotly = ">=5.14.0"
memory_profiler = ">=0.57.0"
Pillow = ">=7.1.2"

[feature.docs.pypi-dependencies]
sphinxcontrib-sass = ">=0.3.4"

[feature.docs.tasks]
docs = { cmd = "spin docs", cwd = "scikit-learn" }

[feature.lint.dependencies]
black = "==24.3.0"
ruff = "==0.5.1"
cython-lint = "==0.15.0"
pre-commit = "*"

[feature.lint.tasks]
lint = { cmd = "pre-commit install && pre-commit run -v --all-files --show-diff-on-failure" }

[feature.tests.dependencies]
pytest = ">=7.1.2"
pytest-cov = ">=2.9.0"
pytest-xdist = ">=2.5.1"
matplotlib = ">=3.3.4"
scikit-image = ">=0.17.2"
pandas = ">=1.1.5"
pyamg = ">=4.0.0"
polars = ">=0.20.30"
pyarrow = ">=12.0.0"
numpydoc = ">=1.2.0"
pooch = ">=1.6.0"

[feature.tests.tasks]
tests = { cmd = "spin test", cwd = "scikit-learn" }

[environments]
lint = ["lint"]
docs = ["build", "docs"]
dev = ["build", "dev", "docs", "lint", "tests"]
tests = ["build", "tests"]
